name: Changed Files Analysis

on:
  pull_request:

permissions:
  pull-requests: read

jobs:
  check_diff:
    runs-on: ubuntu-latest
    name: What's changed?
    env:
      my_secret: ${{ secrets.DUMMY_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46

      - name: Print changed files
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
